---
- name: "Installing git on local/remote machines"
  hosts: localhost
  become: yes
  become_user: ec2-user
  tasks:
  - name: "Installing apache binary on RHEL 7"
    action: yum name=httpd state=present
    when: ansible_os_family == "RedHat"
  - name: Installing apache binary on Ubuntu distribution
    action: apt-get name=apache2 state=present
    when: ansible_os_family == "Debian"
