variable "region" {}
variable "vpc_cidr_test1" {}
variable "vpc_cidr_test2" {}
variable "vpc_pub_sub1_range" {}
variable "vpc_pub_sub2_range" {}
variable "ami" {}
variable "vm_spec" {}
variable "webkey" {}
variable "avail_zone" {}
