pipeline {
    agent any

    tools {
       terraform 'terraform'
    }

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'test', 'prod'], description: 'Select Environment')
        choice(name: 'OPERATION', choices: ['plan', 'apply', 'destroy'], description: 'Select Terraform Actions')
    }

    // environment {
    //     // TF_VAR_environment = params.TF_VAR_environment
    //     AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
    //     AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    // }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Terraform Init') {
            steps {
                script {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Workspace') {
            steps {
                script {
                    // Check if the Terraform workspace exists, create if not
                    def workspaceExists = sh(script: 'terraform workspace select ${ENVIRONMENT} || true', returnStatus: true) == 0

                    if (!workspaceExists) {
                        sh "terraform workspace new ${ENVIRONMENT}"
                    }
                }
            }
        }

        stage('Terraform Operation') {
            steps {
                script {
                    // Run Terraform based on the selected operation
                    switch(params.OPERATION) {
                        case 'plan':
                            sh "terraform plan -var-file='${ENVIRONMENT}.tfvars' -out=tfplan"
                            break
                        case 'apply':
                            sh "terraform plan -var-file='${ENVIRONMENT}.tfvars' -out=tfplan"
                            sh 'terraform apply -auto-approve tfplan'
                            break
                        case 'destroy':
                            sh "terraform destroy -var-file='${ENVIRONMENT}.tfvars' -auto-approve"
                            break
                        default:
                            error "Invalid Terraform operation selected"
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean up artifacts, e.g., the Terraform plan file
            deleteDir()
        }
    }
}
