---
- name: "Playbook to install multiple require packages"
  hosts: localhost
  become: yes
  become_user: ec2-user
  tasks:
  - name: "Install git, tree, make, ntp on local/remote machines"
    action: yum name='{{ item }}' state=present
    loop:
    - git
    - tree
    - make
    - ntp
