---
- name: "print list of indexes using ansible loops"
  hosts: localhost
  become: true
  become_user: ec2-user
  vars:
    list: [10,20,30,40,50]
  tasks:
  - name: "Printing the elements in a list"
    debug:
      msg: "{{ item }}"
    loop: "{{ list }}"