- name: "Setting up httpd webserver"
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/opt/ansible/practical.pem"
    ansible_ssh_user: "ec2-user"
  tasks:
  - name: "Install httpd,tree binaries on Remote machines"
    package:
      name:
        - "httpd"
        - "tree"
      state: present
  - name: "Copy index.html file to config dir of the remote machines"
    copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: "Start httpd services"
    service:
        name: httpd
        state: started
  - name: "Installing Yum packages using loop"
    yum: name={{item}} state=latest
    with_items:
       - wget
       - python36
